// <auto-generated />
using ControleLocacao.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleLocacao.Infra.Data.Migrations
{
    [DbContext(typeof(DbLocacao))]
    partial class DbLocacaoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ControleLocacao.Infra.Data.Tables.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("valorDiaria")
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("ValorDiaria");

                    b.Property<decimal>("valorSeguro")
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("ValorSeguro");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("UK_Categoria_Nome");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("ControleLocacao.Infra.Data.Tables.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("Documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Telefone");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("TipoPessoa");

                    b.HasKey("Id");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("UK_Cliente_Documento");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IX_Cliente_Nome");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("ControleLocacao.Infra.Data.Tables.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("int")
                        .HasColumnName("AnoFabricacao");

                    b.Property<int>("AnoModelo")
                        .HasColumnType("int")
                        .HasColumnName("AnoModelo");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaId");

                    b.Property<ulong>("Inativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(0ul)
                        .HasColumnName("Inativo");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("Marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("Placa");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Versao");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Marca")
                        .HasDatabaseName("IX_Veiculo_Marca");

                    b.HasIndex("Modelo")
                        .HasDatabaseName("IX_Veiculo_Modelo");

                    b.HasIndex("Placa")
                        .HasDatabaseName("IX_Veiculo_Placa");

                    b.HasIndex("Versao")
                        .HasDatabaseName("IX_Veiculo_Versao");

                    b.ToTable("Veiculo", (string)null);
                });

            modelBuilder.Entity("ControleLocacao.Infra.Data.Tables.Veiculo", b =>
                {
                    b.HasOne("ControleLocacao.Infra.Data.Tables.Categoria", "Categoria")
                        .WithMany("veiculo")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ControleLocacao.Infra.Data.Tables.Categoria", b =>
                {
                    b.Navigation("veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
